### ISSUE TITLE
Couple of improvements, if you are interested

### ISSUE THREAD

**Issue by sjawaji** [Sfeir/hello-world-oauth2-endpoints-angularjs#1]
In the authenticate function, 

Following line is executing userAuthenticated function before calling signin.

```
signin(false, userAuthenticated($scope, $location));
```

Change it to

```
signin(false, function () { userAuthenticated($scope, $location); });
```

---

In the queryGreeting function, 

Changes are not reflected in the model.

```
$scope.greeting = resp.greeting;
```

Change it to the following to make sure changes are reflected in the model.

```
$scope.$apply(function (scope) {
            scope.greeting = resp.greeting;
});
```

**Comment by massyl** [comment]
Yep, for 
- Just after $scope.greeting = resp.greeting; i call scope's apply function and it works well. 
  Make a pullRequest of the changes you suggested and i'll merge it.
  thanks
